---
name: "Pull Request: Validate"

on:
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize", "reopened"]

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  simple-checks:
    uses: auricom/containers/.github/workflows/simple-checks.yaml@60139f1456d61d1f6fd09c264ee9651bc0330f08 # main

  get-changed-images:
    uses: auricom/containers/.github/workflows/get-changed-images.yaml@60139f1456d61d1f6fd09c264ee9651bc0330f08 # main

  build-images:
    needs: ["simple-checks", "get-changed-images"]
    if: ${{ needs.get-changed-images.outputs.addedOrModified == 'true' }}
    uses: auricom/containers/.github/workflows/build-images.yaml@60139f1456d61d1f6fd09c264ee9651bc0330f08 # main
    secrets: inherit
    with:
      appsToBuild: "${{ needs.get-changed-images.outputs.addedOrModifiedImages }}"
      pushImages: false
      sendNotifications: false
