---
name: "Release: Schedule"

on:
  workflow_dispatch:
  schedule:
    # NOTE: The longest build for an app is ~1h30m
    # Keep this to run every 2 or more hours to prevent gremlins from spawning
    - cron: "0 1 * * *"

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate-build-matrix:
    name: Generate matrix for building images
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.fetch.outputs.changes }}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          token: ${{ env.TOKEN }}

      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Fetch new app versions
        id: fetch
        run: ./.github/scripts/fetch.sh

  images-build:
    uses: auricom/containers/.github/workflows/action-image-build.yaml@main
    if: needs.generate-build-matrix.outputs.matrix != '[]'
    needs:
      - generate-build-matrix
    with:
      imagesToBuild: "${{ needs.generate-build-matrix.outputs.matrix }}"
      pushImages: "true"
      updateMetadata: "true"
      sendNotification: "true"
    secrets: inherit
